# Generated by Django 4.0.1 on 2024-06-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='spam',
            field=models.IntegerField(default=0),
        ),
    ]
