# Generated by Django 4.0.1 on 2024-06-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_customuser_spam'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('spam_count', models.IntegerField(default=0)),
            ],
        ),
    ]
